name "ckan2"
description "Installs and configures CKAN 2.0 for development."
version "0.1.0"
maintainer "Dmitry Kachaev"
maintainer_email "dmitry.kachaev@gmail.com"
license "Apache v2.0"
depends "git"
depends "python"
depends "postgresql"
